name: Despliegue FTP al Host Gratis

on:
  push:
    branches:
      - master # O el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Subir archivos vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          dangerous-clean-slate: true
          # Excluye cosas que no deben ir al servidor público
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            .env.example
            README_DEPLOY.md
